class tirp {
	tag = "tirp";
class AUR
{
	file = "\TIRP_AdvancedUrbanRappelling\functions";
	class AUR_Add_Player_Actions{postInit=1;};
	class AUR_Advanced_Urban_Rappelling_Install{postInit = 1;};
	class AUR_cleanup_after{};
	class AUR_Climb_Up_Action_Check{};
	class AUR_Climb_Up_Action{};
	class AUR_Current_Weapon_Type_Selected{};
	class AUR_Enable_Rappelling_Animation_Global{};
	class AUR_Enable_Rappelling_Animation{};
	class AUR_find_Nearby_Rappel_Point{};
	class AUR_Get_AI_Units_Ready_To_Rappel{};
	class AUR_Get_Anchor_Point_Player_Looking_At{};
	class AUR_get_player_height_above_ground{};
	class AUR_Get_Trajectory_Angle{};
	class AUR_Has_Addon_Animations_Installed{postInit=1;};
	class AUR_Has_Addon_Sounds_Installed{postInit=1;};
	class AUR_Hide_Object_Global{};
	class AUR_Hint{};
	class AUR_PackRope_Action_Check{};
	class AUR_PackRope_Action{};
	class AUR_Pickup_Rappel_Point_Action_Check{};
	class AUR_Pickup_Rappel_Point_Action{};
	class AUR_Place_Anchor_Action_Check{};
	class AUR_Place_Anchor_Action{};
	class AUR_Place_Rappel_Point_Action_Check{};
	class AUR_Place_Rappel_Point_Action{};
	class AUR_player_Height_Above_Ground{};
	class AUR_Play_3D_Sound{};
	class AUR_Play_Rappelling_Sounds_Global{};
	class AUR_Play_Rappelling_Sounds{};
	class AUR_Prepare_Rope{};
	class AUR_Prepare_Rope_Check{};
	class AUR_rappel_Action_Check{};
	class AUR_Rappel_Action{};
	class AUR_Rappel_AI_Units_Action_Check{};
	class AUR_Rappel_AI_Units_Action{};
	class AUR_Rappel_Climb_To_Top_Action_Check{};
	class AUR_Rappel_Climb_To_Top_Action{};
	class AUR_Rappel_Detach_Action_Check{};
	class AUR_Rappel_Detach_Action{};
	class AUR_Rappel_Unit{};
	class AUR_Rappel{};
	class AUR_RemoteExecServer{};
	class AUR_RemoteExec{};
	class AUR_Tie_In_Action_Check{};
	class AUR_Tie_In_Action{};

};
};